//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallcenterAPI
{
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System;
    using System.Collections.Generic;
    
    public partial class blacklist
    {
        public int idlist { get; set; }
        public long idpersona { get; set; }
        public int idproducto { get; set; }
        public string motivo { get; set; }
    
        public virtual personas personas { get; set; }
        public virtual productos productos { get; set; }

        public class Mapeo
        {
            public Mapeo(EntityTypeBuilder<blacklist> Mapeo)
            {
                Mapeo.HasKey(x => x.idlist);

                Mapeo.HasOne(x => x.personas)
                    .WithMany(x=>x.blacklist)
                    .HasForeignKey(x=>x.idpersona);

                Mapeo.HasOne(x => x.productos)
                    .WithMany(x=>x.blacklist)
                    .HasForeignKey(x=>x.idproducto);



            }
        }
    }
}
