//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


//using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
namespace CallcenterAPI
{
    
 
    public partial class callcenterEntities : DbContext
    {
        public callcenterEntities(DbContextOptions options)
            : base(options)
        {

        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            new agenda.Mapeo(modelBuilder.Entity<agenda>());
            new agendastate.Mapeo(modelBuilder.Entity<agendastate>());
            new argumentos.Mapeo(modelBuilder.Entity<argumentos>());
            new blacklist.Mapeo(modelBuilder.Entity<blacklist>());
            new callstate.Mapeo(modelBuilder.Entity<callstate>());
            new cerrados.Mapeo(modelBuilder.Entity<cerrados>());
            new closestate.Mapeo(modelBuilder.Entity<closestate>());
            new datos.Mapeo(modelBuilder.Entity<datos>());
            new llamados.Mapeo(modelBuilder.Entity<llamados>());
            new perfilesventa.Mapeo(modelBuilder.Entity<perfilesventa>());
            new personas.Mapeo(modelBuilder.Entity<personas>());
            new productos.Mapeo(modelBuilder.Entity<productos>());
            new segstate.Mapeo(modelBuilder.Entity<segstate>());
            new seguimientos.Mapeo(modelBuilder.Entity<seguimientos>());
            new tipousuario.Mapeo(modelBuilder.Entity<tipousuario>());
            new userstate.Mapeo(modelBuilder.Entity<userstate>());
            new usuarios.Mapeo(modelBuilder.Entity<usuarios>());
            new codem.Mapeo(modelBuilder.Entity<codem>());

        }
    
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<agendastate> agendastate { get; set; }
        public virtual DbSet<argumentos> argumentos { get; set; }
        public virtual DbSet<blacklist> blacklist { get; set; }
        public virtual DbSet<callstate> callstate { get; set; }
        public virtual DbSet<cerrados> cerrados { get; set; }
        public virtual DbSet<closestate> closestate { get; set; }
        public virtual DbSet<datos> datos { get; set; }
        public virtual DbSet<llamados> llamados { get; set; }
        public virtual DbSet<perfilesventa> perfilesventa { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<segstate> segstate { get; set; }
        public virtual DbSet<seguimientos> seguimientos { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<userstate> userstate { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<codem> codem { get; set; }
    }
}
