//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallcenterAPI
{
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System;
    using System.Collections.Generic;
    
    public  class llamados
    {
        public int idllamado { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public byte intentos { get; set; }
        public string comentario { get; set; }

        public int idargumento { get; set; }
        public  argumentos argumentos { get; set; }
        public int idstate { get; set; }
        public callstate callstate { get; set; }
        public long idpersona { get; set; }
        public  personas personas { get; set; }
        public int idproducto { get; set; }
        public  productos productos { get; set; }
        public int idusuario { get; set; }
        public  usuarios usuarios { get; set; }

        public class Mapeo
        {
            public Mapeo(EntityTypeBuilder<llamados> Mapeo)
            {
                Mapeo.HasKey(x => x.idllamado);
              
                Mapeo.HasOne(x => x.argumentos)
                    .WithMany(x=>x.llamados)
                    .HasForeignKey(x=>x.idargumento);

                Mapeo.HasOne(x => x.callstate)
                    .WithMany(x => x.llamados)
                    .HasForeignKey(x=>x.idstate);
                     
                Mapeo.HasOne(x => x.personas)
                     .WithMany(x => x.llamados)
                    .HasForeignKey(x => x.idpersona); 

                Mapeo.HasOne(x => x.productos)
                     .WithMany(x => x.llamados)
                    .HasForeignKey(x => x.idproducto); 

                Mapeo.HasOne(x => x.usuarios)
                     .WithMany(x => x.llamados)
                    .HasForeignKey(x => x.idusuario); ;

            }
        }
    }
}
