//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallcenterAPI
{
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System;
    using System.Collections.Generic;
    
    public class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            this.agenda = new HashSet<agenda>();
            this.blacklist = new HashSet<blacklist>();
            this.cerrados = new HashSet<cerrados>();
            this.llamados = new HashSet<llamados>();
            this.seguimientos = new HashSet<seguimientos>();
        }

        public long idpersona { get; set; }
        public Nullable<int> idperfilventa { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string telefono3 { get; set; }
        public string telefono4 { get; set; }
        public string telefono5 { get; set; }
        public string telefono6 { get; set; }
        public Nullable<byte> telefonodefault { get; set; }
        public string dni { get; set; }
        public string cuil { get; set; }
        public string provincia { get; set; }
        public string partido { get; set; }
        public string localidad { get; set; }
        public string zona { get; set; }
        public string calle { get; set; }
        public string altura { get; set; }
        public string piso { get; set; }
        public string dpto { get; set; }
        public string cp { get; set; }
        public string cbu { get; set; }
        public string tarjeta { get; set; }
        public string codtarjeta { get; set; }
        public Nullable<int> codobrasocial { get; set; }
        public string condicionafip { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public string email { get; set; }
        public Nullable<bool> used { get; set; }
        public Nullable<bool> aportes { get; set; }
        public Nullable<System.DateTime> cambioos { get; set; }
        public Nullable<System.DateTime> lastcall { get; set; }
        public Nullable<System.DateTime> lastcom { get; set; }
        public Nullable<bool> conformeos { get; set; }
        public Nullable<bool> apto { get; set; }
        public Nullable<bool> hijos { get; set; }
        public string canthijos { get; set; }
        public Nullable<bool> pareja { get; set; }
        public Nullable<int> idbd { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blacklist> blacklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerrados> cerrados { get; set; }
        public virtual codem codem { get; set; }
        public virtual datos datos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llamados> llamados { get; set; }
        public virtual perfilesventa perfilesventa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientos> seguimientos { get; set; }

        public class Mapeo
        {
            public Mapeo(EntityTypeBuilder<personas> Mapeo)
            {
                Mapeo.HasKey(x => x.idpersona);
                Mapeo.HasOne(x => x.perfilesventa)
                    .WithMany(x => x.personas)
                    .HasForeignKey(x => x.idperfilventa); 

                Mapeo.HasOne(x => x.datos)
                    .WithMany(x => x.personas)
                    .HasForeignKey(x => x.idbd);

                Mapeo.HasOne(x => x.codem)
                    .WithMany(x => x.personas)
                    .HasForeignKey(x => x.codobrasocial);




            }
        }
    }
}
