//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallcenterAPI
{
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System;
    using System.Collections.Generic;
    
    public class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.agenda = new HashSet<agenda>();
            this.cerrados = new HashSet<cerrados>();
            this.llamados = new HashSet<llamados>();
            this.seguimientos = new HashSet<seguimientos>();
        }

        public int iduser { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string turno { get; set; }
        public string token { get; set; }
        public int idtipouser { get; set; }
        public int idstate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerrados> cerrados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<llamados> llamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientos> seguimientos { get; set; }
        public  tipousuario tipousuario { get; set; }
        public userstate userstate { get; set; }

        public class Mapeo
        {
            public Mapeo(EntityTypeBuilder<usuarios> Mapeo)
            {
                Mapeo.HasKey(x => x.iduser);
                Mapeo.HasOne(x => x.tipousuario).
                    WithMany(x => x.usuarios)
                    .HasForeignKey(x => x.iduser);

                Mapeo.HasOne(x => x.userstate).
                    WithMany(x => x.usuarios)
                    .HasForeignKey(x => x.idstate);
               

            }
        }
    }
}
